TAB_ID_SUMMARY = 1
TAB_ID_GENRES = 2
TAB_ID_SOURCES = 3
TAB_ID_TYPES = 4
TAB_ID_STUDIOS = 5

TAB_ID_PREDICTIONS = 1
TAB_ID_PERFORMANCE = 2

HELP_TEXT = list()
HELP_TEXT$summary[1] = 'This plot shows how scores have changed over time.  The red line is the median score.  You can see curves for mean, min, and max scores with the options tooltip.  Click and drag to zoom in, and double click to zoom out.'
HELP_TEXT$summary[2] = 'This plot shows how the number of viewers has changed over time.  The red line is the median score.  You can see curves for mean, min, and max scores with the options tooltip.  Click and drag to zoom in, and double click to zoom out.'
HELP_TEXT$summary[3] = 'This plot shows how number of episodes has changed over time.  The red line is the median score.  You can see curves for mean, min, and max scores with the options tooltip.  Click and drag to zoom in, and double click to zoom out.'
HELP_TEXT$summary[4] = 'This chart shows the proportions of all anime types throughout time.  The length of a color segment down a bar denotes the proportion of shows that aired in the corresponding year of the associated type.'
HELP_TEXT$summary[5] = 'This chart shows the proportions of source material throughout time.  The length of a color segment down a bar denotes the proportion of shows that aired in the corresponding year that were based on the associated source material.'
HELP_TEXT$summary[6] = 'This plot shows the performance of a studio throughout time.  The y-axis represents percentiles.  The red curve is the performance in terms of number of shows produced.  The blue curve is performance in terms of median score.  When a point is at y = p, this means the studio did better than p*100% of all studios (or did worse than (1-p)100% of all studios).  When \'All studios\' is selected, the interpretation of the plot changes to the performance of the industry.  In this case, when (x, y) = (t, p), this means the industry did better in year t than p*100% of all other years.  The closer to 1.0 a point is, the better the studio or industry performed for the associated year.'
HELP_TEXT$summary[7] = 'This plot shows the same information as the above one, but using different axes.  The x-axis is the proportion of studios that produced fewer anime than the currently selected studio.  The y-axis is the proportion of studios that had lower median scores than the selected studio.  The points are shown as years and separated into quadrants to easily see which years were best or worst for the studio.  The dashed lines intersect at the median performance levels of the studio.  This allows the following interpretations: years in the first quadrant are those in which the studio made more shows and got better scores than usual (the golden years).  Years in the second quadrant are those in which the studio made fewer shows and got better scores than usual.  Third quadrant years are those in which the studio made less shows and got lower scores than usual (the dark ages).  Fourth quadrant years are those in which the studio made more shows and got lower scores than usual.  The years in red are the most recent five years, and those in blue are following years (they cover the most recent decade).  When \'All studios\' is selected, the interpretation changes as in the above plot, so that years in quadrant Q are those in which the industry performed as explained earlier in this paragraph.'

HELP_TEXT$genres[1] = 'This chart shows the proportion of shows made by the studio that contain a genre, sorted from highest to lowest proportion.  Red bars denote the core genres of the studio.  Together, at least 50% of the studio\'s shows has at least one of these genres.  The blue bars are the "rare gem" genres.  These are genres that the studio seldomly uses, but when present, the show tends to be better than their usual show (in other words, infrequent, but good).  The green bars denote the "hidden gem" genres.  Shows with these genres present are better than the studio\'s typical show, but are watched by a relatively few number of people.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[2] = 'This chart shows the median scores of shows made by the studio that contain a genre, sorted from highest to lowest score.  The dashed line is the median score of the studio, and the dotted line is the median score of the industry as a whole.  The colors are as explained in the first plot.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[3] = 'This plot shows the performance of shows with a given genre throughout time.  The left y-axis is the proportion of shows that contain the genre.  The solid line is associated with this axis.  The right y-axis is the median score of the shows that contain the genre.  The dashed line is associated with this axis. Genres can be selected through the options tooltip.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[4] = 'This heatmap shows the proportion of each genre throughout time.  The more white a block is, the higher the proportion of shows that contain the genre in the associated year.'
HELP_TEXT$genres[5] = 'This chart plots each genre according to its quality and popularity.  The dashed lines intersect at the median score and median views for all shows of the studio.  Genres in the first quadrant are associated with shows that are watched by many people and have higher scores than their typical show.  Second quadrant genres are in shows that have higher scores than usual, but are watched by a relatively low number of people.  Third quadrant genres have both lower viewership than normal, and lower scores than normal.  Genres in the fourth quadrant have lower scores than usual but are watched by more people than is typical for the studio.  Green genres are those in the second quadrant.  Blue genres are in the first and second quadrants (these are infrequently used by the studio).  Red genres are those that are frequently used by the studio (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[6] = 'This chart plots each genre according to its quality and quantity.  The dashed lines intersect at the median score for all shows of the studio and the median proportion of shows made by the studio that contain a genre.  Genres to the left of the vertical dashed line are seldomly used by the studio.  Those to the right are frequently used.  Genres above the horizontal dashed line are in shows that have higher scores that is usual for the studio.  Those below usually result in shows with lower scores.  Green genres are above the horizontal dashed line.  Blue genres are as well, but are only in the second quadrant (high scores, but seldomly used).  Red genres are the furthest to the right of the vertical dashed line (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[7] = 'This chart plots each genre according to its forcasted quality and quantity.  The x-axis represents the change in proportion of shows that contain the genre.  The y-axis represents the change in median score of the shows that contain the genre.  The colors of the genres are as explained in previous plots.  Click and drag to zoom in.  Double click to zoom out.'
