TAB_ID_SUMMARY = 1
TAB_ID_GENRES = 2
TAB_ID_SOURCES = 3
TAB_ID_TYPES = 4
TAB_ID_STUDIOS = 5

TAB_ID_PREDICTIONS = 1
TAB_ID_PERFORMANCE = 2

HELP_TEXT = list()
HELP_TEXT$summary[1] = 'This plot shows how scores have changed over time.  The red line is the median score.  You can see curves for mean, min, and max scores with the options tooltip.  Click and drag to zoom in, and double click to zoom out.'
HELP_TEXT$summary[2] = 'This plot shows how the number of viewers has changed over time.  The red line is the median score.  You can see curves for mean, min, and max scores with the options tooltip.  Click and drag to zoom in, and double click to zoom out.'
HELP_TEXT$summary[3] = 'This plot shows how number of episodes has changed over time.  The red line is the median score.  You can see curves for mean, min, and max scores with the options tooltip.  Click and drag to zoom in, and double click to zoom out.'
HELP_TEXT$summary[4] = 'This chart shows the proportions of all anime types throughout time.  The length of a color segment down a bar denotes the proportion of shows that aired in the corresponding year of the associated type.'
HELP_TEXT$summary[5] = 'This chart shows the proportions of source material throughout time.  The length of a color segment down a bar denotes the proportion of shows that aired in the corresponding year that were based on the associated source material.'
HELP_TEXT$summary[6] = 'This plot shows the performance of a studio throughout time.  The y-axis represents percentiles.  The red curve is the performance in terms of number of shows produced.  The blue curve is performance in terms of median score.  When a point is at y = p, this means the studio did better than p*100% of all studios (or did worse than (1-p)100% of all studios).  When \'All studios\' is selected, the interpretation of the plot changes to the performance of the industry.  In this case, when (x, y) = (t, p), this means the industry did better in year t than p*100% of all other years.  The closer to 1.0 a point is, the better the studio or industry performed for the associated year.'
HELP_TEXT$summary[7] = 'This plot shows the same information as the above one, but using different axes.  The x-axis is the proportion of studios that produced fewer anime than the currently selected studio.  The y-axis is the proportion of studios that had lower median scores than the selected studio.  The points are shown as years and separated into quadrants to easily see which years were best or worst for the studio.  The dashed lines intersect at the median performance levels of the studio.  This allows the following interpretations: years in the first quadrant are those in which the studio made more shows and got better scores than usual (the golden years).  Years in the second quadrant are those in which the studio made fewer shows and got better scores than usual.  Third quadrant years are those in which the studio made less shows and got lower scores than usual (the dark ages).  Fourth quadrant years are those in which the studio made more shows and got lower scores than usual.  The years in red are the most recent five years, and those in blue are following years (they cover the most recent decade).  When \'All studios\' is selected, the interpretation changes as in the above plot, so that years in quadrant Q are those in which the industry performed as explained earlier in this paragraph.'


HELP_TEXT$genres[1] = 'This chart shows the proportion of shows made by the studio that contain a genre, sorted from highest to lowest proportion.  Red bars denote the core genres of the studio.  Together, at least 50% of the studio\'s shows has at least one of these genres.  The blue bars are the "rare gem" genres.  These are genres that the studio seldomly uses, but when present, the show tends to be better than their usual show (in other words, infrequent, but good).  The green bars denote the "hidden gem" genres.  Shows with these genres present are better than the studio\'s typical show, but are watched by a relatively few number of people.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[2] = 'This chart shows the median scores of shows made by the studio that contain a genre, sorted from highest to lowest score.  The dashed line is the median score of the studio, and the dotted line is the median score of the industry as a whole.  The colors are as explained in the first plot.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[3] = 'This plot shows the performance of shows with a given genre throughout time.  The left y-axis is the proportion of shows that contain the genre.  The solid line is associated with this axis.  The right y-axis is the median score of the shows that contain the genre.  The dashed line is associated with this axis. Genres can be selected through the options tooltip.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[4] = 'This heatmap shows the proportion of each genre throughout time.  The more white a block is, the higher the proportion of shows that contain the genre in the associated year.'
HELP_TEXT$genres[5] = 'This chart plots each genre according to its quality and popularity.  The dashed lines intersect at the median score and median views for all shows of the studio.  Genres in the first quadrant are associated with shows that are watched by many people and have higher scores than their typical show.  Second quadrant genres are in shows that have higher scores than usual, but are watched by a relatively low number of people.  Third quadrant genres have both lower viewership than normal, and lower scores than normal.  Genres in the fourth quadrant have lower scores than usual but are watched by more people than is typical for the studio.  Green genres are those in the second quadrant.  Blue genres are in the first and second quadrants (these are infrequently used by the studio).  Red genres are those that are frequently used by the studio (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[6] = 'This chart plots each genre according to its quality and quantity.  The dashed lines intersect at the median score for all shows of the studio and the median proportion of shows made by the studio that contain a genre.  Genres to the left of the vertical dashed line are seldomly used by the studio.  Those to the right are frequently used.  Genres above the horizontal dashed line are in shows that have higher scores that is usual for the studio.  Those below usually result in shows with lower scores.  Green genres are above the horizontal dashed line.  Blue genres are as well, but are only in the second quadrant (high scores, but seldomly used).  Red genres are the furthest to the right of the vertical dashed line (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[7] = 'This chart plots each genre according to its forcasted quality and quantity.  The x-axis represents the change in proportion of shows that contain the genre.  The y-axis represents the change in median score of the shows that contain the genre.  The colors of the genres are as explained in previous plots.  Click and drag to zoom in.  Double click to zoom out.'


HELP_TEXT$source[1] = 'This chart shows the proportion of shows made by the studio that are based on a source material, sorted from highest to lowest proportion.  Red bars denote the core source materials of the studio.  Together, at least 50% of the studio\'s shows are based on these source materials.  The blue bars are the "rare gem" source materials.  These are source materials that the studio seldomly uses, but when used, the show tends to be better than their usual show (in other words, infrequent, but good).  The green bars denote the "hidden gem" source materials.  Shows based on these source materials are better than the studio\'s typical show, but are watched by a relatively few number of people.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$source[2] = 'This chart shows the median scores of shows made by the studio that are based on a source material, sorted from highest to lowest score.  The dashed line is the median score of the studio, and the dotted line is the median score of the industry as a whole.  The colors are as explained in the first plot.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$source[3] = 'This plot shows the performance of shows based on a source material throughout time.  The left y-axis is the proportion of shows that are based on the selected source material.  The solid line is associated with this axis.  The right y-axis is the median score of the shows that are based on the selected source material.  The dashed line is associated with this axis. Source materials can be selected through the options tooltip.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$source[4] = 'This heatmap shows the proportion of each source material throughout time.  The more white a block is, the higher the proportion of shows that are based on a source material in the associated year.'
HELP_TEXT$source[5] = 'This chart plots each source material according to its quality and popularity.  The dashed lines intersect at the median score and median views for all shows of the studio.  Source materials in the first quadrant are associated with shows that are watched by many people and have higher scores than their typical show.  Second quadrant source materials result in shows that have higher scores than usual, but are watched by a relatively low number of people.  Third quadrant source materials have both lower viewership than normal, and lower scores than normal.  Source materials in the fourth quadrant have lower scores than usual but are watched by more people than is typical for the studio.  Green source materials are those in the second quadrant.  Blue source materials are in the first and second quadrants (these are infrequently used by the studio).  Red source materials are those that are frequently used by the studio (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$source[6] = 'This chart plots each source material according to its quality and quantity.  The dashed lines intersect at the median score for all shows of the studio and the median proportion of shows made by the studio that are based on a source material.  Source materials to the left of the vertical dashed line are seldomly used by the studio.  Those to the right are frequently used.  Source materials above the horizontal dashed line result in shows that have higher scores than is usual for the studio.  Those below usually result in shows with lower scores.  Green source materials are above the horizontal dashed line.  Blue source materials are as well, but are only in the second quadrant (high scores, but seldomly used).  Red source materials are the furthest to the right of the vertical dashed line (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$source[7] = 'This chart plots each source material according to its forcasted quality and quantity.  The x-axis represents the change in proportion of shows that are based on the source material.  The y-axis represents the change in median score of the shows that are based on the source material.  The colors of the source materials are as explained in previous plots.  Click and drag to zoom in.  Double click to zoom out.'


HELP_TEXT$type[1] = 'This chart shows the proportion of shows made by the studio that are of a type, sorted from highest to lowest proportion.  Red bars denote the core types of the studio.  Together, at least 50% of the studio\'s shows are of these types.  The blue bars are the "rare gem" types.  These are types that the studio seldomly animates, but when it does, the show tends to be better than their usual show (in other words, infrequent, but good).  The green bars denote the "hidden gem" types.  Shows under these types are better than the studio\'s typical show, but are watched by a relatively few number of people.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$type[2] = 'This chart shows the median scores of shows made by the studio that for each type, sorted from highest to lowest score.  The dashed line is the median score of the studio, and the dotted line is the median score of the industry as a whole.  The colors are as explained in the first plot.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$type[3] = 'This plot shows the performance of shows with a given type throughout time.  The left y-axis is the proportion of shows that are of the selected type.  The solid line is associated with this axis.  The right y-axis is the median score of the shows that are of the selected type.  The dashed line is associated with this axis. Types can be selected through the options tooltip.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$type[4] = 'This heatmap shows the proportion of each type throughout time.  The more white a block is, the higher the proportion of shows of the type in the associated year.'
HELP_TEXT$type[5] = 'This chart plots each type according to its quality and popularity.  The dashed lines intersect at the median score and median views for all shows of the studio.  Types in the first quadrant are associated with shows that are watched by many people and have higher scores than their typical show.  Second quadrant types result in shows that have higher scores than usual, but are watched by a relatively low number of people.  Third quadrant types have both lower viewership than normal, and lower scores than normal.  Types in the fourth quadrant have lower scores than usual but are watched by more people than is typical for the studio.  Green types are those in the second quadrant.  Blue types are in the first and second quadrants (these are infrequently used by the studio).  Red types are those that are frequently animated by the studio (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$type[6] = 'This chart plots each type according to its quality and quantity.  The dashed lines intersect at the median score for all shows of the studio and the median proportion of shows made by the studio that contain a type  Types to the left of the vertical dashed line are seldomly animated by the studio.  Those to the right are frequently animated.  Types above the horizontal dashed line result in shows that have higher scores that is usual for the studio.  Those below usually result in shows with lower scores.  Green types are above the horizontal dashed line.  Blue types are as well, but are only in the second quadrant (high scores, but seldomly used).  Red types are the furthest to the right of the vertical dashed line (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$type[7] = 'This chart plots each type according to its forcasted quality and quantity.  The x-axis represents the change in proportion of shows that are of the type.  The y-axis represents the change in median score of the shows that are of the type.  The colors of the types are as explained in previous plots.  Click and drag to zoom in.  Double click to zoom out.'


HELP_TEXT$studio[1] = 'This chart shows the proportion of shows made by each studio , sorted from highest to lowest proportion.  Red bars denote the core studios.  Together, at least 50% of all shows were animated by these studios.  The blue bars are the "rare gem" studios.  These are studios that seldomly create shows, but when they do, their shows tend to be better than usual shows (in other words, infrequent, but good).  The green bars denote the "hidden gem" studios.  Shows animated by these studios are better than the typical show, but are watched by a relatively few number of people.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$studio[2] = 'This chart shows the median scores of shows over all studios, sorted from highest to lowest score.  The dashed and dotted lines are the median score (they are the same).  The colors are as explained in the first plot.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$studio[3] = 'This plot shows the performance of shows with a given studio throughout time.  The left y-axis is the proportion of shows animated by the selected studio.  The solid line is associated with this axis.  The right y-axis is the median score of the shows animated by the selected studio.  The dashed line is associated with this axis. Studios can be selected through the options tooltip.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$studio[4] = 'This heatmap shows the proportion of each studio throughout time.  The more white a block is, the higher the number of shows animated by the studio in the associated year.'
HELP_TEXT$studio[5] = 'This chart plots each studio according to its quality and popularity.  The dashed lines intersect at the median score and median views over all shows of all studios.  Studios in the first quadrant are associated with shows that are watched by many people and have higher scores than the typical show.  Second quadrant studios animate shows that have higher scores than usual, but are watched by a relatively low number of people.  Third quadrant studios both have lower viewership than normal, and receive lower scores than normal.  Studios in the fourth quadrant make shows that receive lower scores than usual but are watched by more people than is typical for the industry.  Green studios are those in the second quadrant.  Blue studios are in the first and second quadrants (these infrequently animate shows).  Red studios are those frequently animate shows (together, they have animated at least 50% of all shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$studio[6] = 'This chart plots each studio according to its quality and quantity.  The dashed lines intersect at the median score over all shows and the median proportion of shows animated by a studio.  Studios to the left of the vertical dashed line seldomly animate shows.  Those to the right frequently animate shows.  Studios above the horizontal dashed line animate shows that have higher scores than is usual for the industry.  Those below usually animate shows with lower scores.  Green studios are above the horizontal dashed line.  Blue studios are as well, but are only in the second quadrant (high scores, but seldomly animate).  Red studios are the furthest to the right of the vertical dashed line (together, these studios have animated at least 50% of all anime).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$studio[7] = 'This chart plots each studio according to its forcasted quality and quantity.  The x-axis represents the change in the proportion of shows animated by a studio.  The y-axis represents the change in median score of the shows that are animated by a studio.  The colors of the studios are as explained in previous plots.  Click and drag to zoom in.  Double click to zoom out.'

