# This list acts as an enum to refer to a tab.  If code needs
# to reference a specific tab, it should do so using this enum.
tabsEnum = list()
tabsEnum$SUMMARY = 1
tabsEnum$GENRES = 2
tabsEnum$SOURCES = 3
tabsEnum$TYPES = 4
tabsEnum$STUDIOS = 5
tabsEnum$PREDICTIONS = 6
tabsEnum$PERFORMANCE = 7

# This list is an enum to refer to a plot.  If code needs to
# refer to a specific plot, it should do so with this enum.
plotsEnum = list()
plotsEnum$SCORE_VS_TIME = 1
plotsEnum$VIEWS_VS_TIME = 2
plotsEnum$EPS_VS_TIME = 3
plotsEnum$TYPEPROP_VS_TIME = 4
plotsEnum$SOURCEPROP_VS_TIME = 5
plotsEnum$PERFORMANCE_VS_TIME = 6
plotsEnum$SCORE_PERC_VS_SHOW_PERC = 7
plotsEnum$PROP_BARCHART = 8
plotsEnum$SCORE_VS_CATEGORY = 9
plotsEnum$CATEGORY_PERF_VS_TIME = 10
plotsEnum$CATEGORY_SCORE_VS_VIEWS = 11
plotsEnum$CATEGORY_SCORE_VS_PROP = 12
plotsEnum$CATEGORY_SCORE_SLOPE_VS_PROP_SLOPE = 13
plotsEnum$CATEGORY_PROP_HEATMAP = 14
# Each element of this list corresponds to a tab in the
# Stats page.  The elements of those elements are help
# text for the corresponding plot.
HELP_TEXT = list()
HELP_TEXT$summary[1] = 'This plot shows how scores have changed over time.  The red line is the median score.  You can see curves for mean, min, and max scores with the options tooltip.  Click and drag to zoom in, and double click to zoom out.'
HELP_TEXT$summary[2] = 'This plot shows how the number of viewers has changed over time.  The red line is the median score.  You can see curves for mean, min, and max scores with the options tooltip.  Click and drag to zoom in, and double click to zoom out.'
HELP_TEXT$summary[3] = 'This plot shows how number of episodes has changed over time.  The red line is the median score.  You can see curves for mean, min, and max scores with the options tooltip.  Click and drag to zoom in, and double click to zoom out.'
HELP_TEXT$summary[4] = 'This chart shows the proportions of all anime types throughout time.  The length of a color segment down a bar denotes the proportion of shows that aired in the corresponding year of the associated type.'
HELP_TEXT$summary[5] = 'This chart shows the proportions of source material throughout time.  The length of a color segment down a bar denotes the proportion of shows that aired in the corresponding year that were based on the associated source material.'
HELP_TEXT$summary[6] = 'This plot shows the performance of a studio throughout time.  The y-axis represents percentiles.  The red curve is the performance in terms of number of shows produced.  The blue curve is performance in terms of median score.  When a point is at y = p, this means the studio did better than p*100% of all studios (or did worse than (1-p)100% of all studios).  When \'All studios\' is selected, the interpretation of the plot changes to the performance of the industry.  In this case, when (x, y) = (t, p), this means the industry did better in year t than p*100% of all other years.  The closer to 1.0 a point is, the better the studio or industry performed for the associated year.'
HELP_TEXT$summary[7] = 'This plot shows the same information as the above one, but using different axes.  The x-axis is the proportion of studios that produced fewer anime than the currently selected studio.  The y-axis is the proportion of studios that had lower median scores than the selected studio.  The points are shown as years and separated into quadrants to easily see which years were best or worst for the studio.  The dashed lines intersect at the median performance levels of the studio.  This allows the following interpretations: years in the first quadrant are those in which the studio made more shows and got better scores than usual (the golden years).  Years in the second quadrant are those in which the studio made fewer shows and got better scores than usual.  Third quadrant years are those in which the studio made less shows and got lower scores than usual (the dark ages).  Fourth quadrant years are those in which the studio made more shows and got lower scores than usual.  The years in red are the most recent five years, and those in blue are following years (they cover the most recent decade).  When \'All studios\' is selected, the interpretation changes as in the above plot, so that years in quadrant Q are those in which the industry performed as explained earlier in this paragraph.'


HELP_TEXT$genres[1] = 'This chart shows the proportion of shows made by the studio that contain a genre, sorted from highest to lowest proportion.  Red bars denote the core genres of the studio.  Together, at least 50% of the studio\'s shows has at least one of these genres.  The blue bars are the "rare gem" genres.  These are genres that the studio seldomly uses, but when present, the show tends to be better than their usual show (in other words, infrequent, but good).  The green bars denote the "hidden gem" genres.  Shows with these genres present are better than the studio\'s typical show, but are watched by a relatively few number of people.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[2] = 'This chart shows the median scores of shows made by the studio that contain a genre, sorted from highest to lowest score.  The dashed line is the median score of the studio, and the dotted line is the median score of the industry as a whole.  The colors are as explained in the first plot.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[3] = 'This plot shows the performance of shows with a given genre throughout time.  The left y-axis is the proportion of shows that contain the genre.  The solid line is associated with this axis.  The right y-axis is the median score of the shows that contain the genre.  The dashed line is associated with this axis. Genres can be selected through the options tooltip.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[4] = 'This heatmap shows the proportion of each genre throughout time.  The more white a block is, the higher the proportion of shows that contain the genre in the associated year.'
HELP_TEXT$genres[5] = 'This chart plots each genre according to its quality and popularity.  The dashed lines intersect at the median score and median views for all shows of the studio.  Genres in the first quadrant are associated with shows that are watched by many people and have higher scores than their typical show.  Second quadrant genres are in shows that have higher scores than usual, but are watched by a relatively low number of people.  Third quadrant genres have both lower viewership than normal, and lower scores than normal.  Genres in the fourth quadrant have lower scores than usual but are watched by more people than is typical for the studio.  Green genres are those in the second quadrant.  Blue genres are in the first and second quadrants (these are infrequently used by the studio).  Red genres are those that are frequently used by the studio (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[6] = 'This chart plots each genre according to its quality and quantity.  The dashed lines intersect at the median score for all shows of the studio and the median proportion of shows made by the studio that contain a genre.  Genres to the left of the vertical dashed line are seldomly used by the studio.  Those to the right are frequently used.  Genres above the horizontal dashed line are in shows that have higher scores that is usual for the studio.  Those below usually result in shows with lower scores.  Green genres are above the horizontal dashed line.  Blue genres are as well, but are only in the second quadrant (high scores, but seldomly used).  Red genres are the furthest to the right of the vertical dashed line (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$genres[7] = 'This chart plots each genre according to its forcasted quality and quantity.  The x-axis represents the change in proportion of shows that contain the genre.  The y-axis represents the change in median score of the shows that contain the genre.  The colors of the genres are as explained in previous plots.  Click and drag to zoom in.  Double click to zoom out.'


HELP_TEXT$source[1] = 'This chart shows the proportion of shows made by the studio that are based on a source material, sorted from highest to lowest proportion.  Red bars denote the core source materials of the studio.  Together, at least 50% of the studio\'s shows are based on these source materials.  The blue bars are the "rare gem" source materials.  These are source materials that the studio seldomly uses, but when used, the show tends to be better than their usual show (in other words, infrequent, but good).  The green bars denote the "hidden gem" source materials.  Shows based on these source materials are better than the studio\'s typical show, but are watched by a relatively few number of people.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$source[2] = 'This chart shows the median scores of shows made by the studio that are based on a source material, sorted from highest to lowest score.  The dashed line is the median score of the studio, and the dotted line is the median score of the industry as a whole.  The colors are as explained in the first plot.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$source[3] = 'This plot shows the performance of shows based on a source material throughout time.  The left y-axis is the proportion of shows that are based on the selected source material.  The solid line is associated with this axis.  The right y-axis is the median score of the shows that are based on the selected source material.  The dashed line is associated with this axis. Source materials can be selected through the options tooltip.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$source[4] = 'This heatmap shows the proportion of each source material throughout time.  The more white a block is, the higher the proportion of shows that are based on a source material in the associated year.'
HELP_TEXT$source[5] = 'This chart plots each source material according to its quality and popularity.  The dashed lines intersect at the median score and median views for all shows of the studio.  Source materials in the first quadrant are associated with shows that are watched by many people and have higher scores than their typical show.  Second quadrant source materials result in shows that have higher scores than usual, but are watched by a relatively low number of people.  Third quadrant source materials have both lower viewership than normal, and lower scores than normal.  Source materials in the fourth quadrant have lower scores than usual but are watched by more people than is typical for the studio.  Green source materials are those in the second quadrant.  Blue source materials are in the first and second quadrants (these are infrequently used by the studio).  Red source materials are those that are frequently used by the studio (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$source[6] = 'This chart plots each source material according to its quality and quantity.  The dashed lines intersect at the median score for all shows of the studio and the median proportion of shows made by the studio that are based on a source material.  Source materials to the left of the vertical dashed line are seldomly used by the studio.  Those to the right are frequently used.  Source materials above the horizontal dashed line result in shows that have higher scores than is usual for the studio.  Those below usually result in shows with lower scores.  Green source materials are above the horizontal dashed line.  Blue source materials are as well, but are only in the second quadrant (high scores, but seldomly used).  Red source materials are the furthest to the right of the vertical dashed line (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$source[7] = 'This chart plots each source material according to its forcasted quality and quantity.  The x-axis represents the change in proportion of shows that are based on the source material.  The y-axis represents the change in median score of the shows that are based on the source material.  The colors of the source materials are as explained in previous plots.  Click and drag to zoom in.  Double click to zoom out.'


HELP_TEXT$type[1] = 'This chart shows the proportion of shows made by the studio that are of a type, sorted from highest to lowest proportion.  Red bars denote the core types of the studio.  Together, at least 50% of the studio\'s shows are of these types.  The blue bars are the "rare gem" types.  These are types that the studio seldomly animates, but when it does, the show tends to be better than their usual show (in other words, infrequent, but good).  The green bars denote the "hidden gem" types.  Shows under these types are better than the studio\'s typical show, but are watched by a relatively few number of people.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$type[2] = 'This chart shows the median scores of shows made by the studio that for each type, sorted from highest to lowest score.  The dashed line is the median score of the studio, and the dotted line is the median score of the industry as a whole.  The colors are as explained in the first plot.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$type[3] = 'This plot shows the performance of shows with a given type throughout time.  The left y-axis is the proportion of shows that are of the selected type.  The solid line is associated with this axis.  The right y-axis is the median score of the shows that are of the selected type.  The dashed line is associated with this axis. Types can be selected through the options tooltip.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$type[4] = 'This heatmap shows the proportion of each type throughout time.  The more white a block is, the higher the proportion of shows of the type in the associated year.'
HELP_TEXT$type[5] = 'This chart plots each type according to its quality and popularity.  The dashed lines intersect at the median score and median views for all shows of the studio.  Types in the first quadrant are associated with shows that are watched by many people and have higher scores than their typical show.  Second quadrant types result in shows that have higher scores than usual, but are watched by a relatively low number of people.  Third quadrant types have both lower viewership than normal, and lower scores than normal.  Types in the fourth quadrant have lower scores than usual but are watched by more people than is typical for the studio.  Green types are those in the second quadrant.  Blue types are in the first and second quadrants (these are infrequently used by the studio).  Red types are those that are frequently animated by the studio (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$type[6] = 'This chart plots each type according to its quality and quantity.  The dashed lines intersect at the median score for all shows of the studio and the median proportion of shows made by the studio that contain a type  Types to the left of the vertical dashed line are seldomly animated by the studio.  Those to the right are frequently animated.  Types above the horizontal dashed line result in shows that have higher scores that is usual for the studio.  Those below usually result in shows with lower scores.  Green types are above the horizontal dashed line.  Blue types are as well, but are only in the second quadrant (high scores, but seldomly used).  Red types are the furthest to the right of the vertical dashed line (together found in at least 50% of the studio\'s shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$type[7] = 'This chart plots each type according to its forcasted quality and quantity.  The x-axis represents the change in proportion of shows that are of the type.  The y-axis represents the change in median score of the shows that are of the type.  The colors of the types are as explained in previous plots.  Click and drag to zoom in.  Double click to zoom out.'


HELP_TEXT$studio[1] = 'This chart shows the proportion of shows made by each studio , sorted from highest to lowest proportion.  Red bars denote the core studios.  Together, at least 50% of all shows were animated by these studios.  The blue bars are the "rare gem" studios.  These are studios that seldomly create shows, but when they do, their shows tend to be better than usual shows (in other words, infrequent, but good).  The green bars denote the "hidden gem" studios.  Shows animated by these studios are better than the typical show, but are watched by a relatively few number of people.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$studio[2] = 'This chart shows the median scores of shows over all studios, sorted from highest to lowest score.  The dashed and dotted lines are the median score (they are the same).  The colors are as explained in the first plot.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$studio[3] = 'This plot shows the performance of shows with a given studio throughout time.  The left y-axis is the proportion of shows animated by the selected studio.  The solid line is associated with this axis.  The right y-axis is the median score of the shows animated by the selected studio.  The dashed line is associated with this axis. Studios can be selected through the options tooltip.  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$studio[4] = 'This heatmap shows the proportion of each studio throughout time.  The more white a block is, the higher the number of shows animated by the studio in the associated year.'
HELP_TEXT$studio[5] = 'This chart plots each studio according to its quality and popularity.  The dashed lines intersect at the median score and median views over all shows of all studios.  Studios in the first quadrant are associated with shows that are watched by many people and have higher scores than the typical show.  Second quadrant studios animate shows that have higher scores than usual, but are watched by a relatively low number of people.  Third quadrant studios both have lower viewership than normal, and receive lower scores than normal.  Studios in the fourth quadrant make shows that receive lower scores than usual but are watched by more people than is typical for the industry.  Green studios are those in the second quadrant.  Blue studios are in the first and second quadrants (these infrequently animate shows).  Red studios are those frequently animate shows (together, they have animated at least 50% of all shows).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$studio[6] = 'This chart plots each studio according to its quality and quantity.  The dashed lines intersect at the median score over all shows and the median proportion of shows animated by a studio.  Studios to the left of the vertical dashed line seldomly animate shows.  Those to the right frequently animate shows.  Studios above the horizontal dashed line animate shows that have higher scores than is usual for the industry.  Those below usually animate shows with lower scores.  Green studios are above the horizontal dashed line.  Blue studios are as well, but are only in the second quadrant (high scores, but seldomly animate).  Red studios are the furthest to the right of the vertical dashed line (together, these studios have animated at least 50% of all anime).  Click and drag to zoom in.  Double click to zoom out.'
HELP_TEXT$studio[7] = 'This chart plots each studio according to its forcasted quality and quantity.  The x-axis represents the change in the proportion of shows animated by a studio.  The y-axis represents the change in median score of the shows that are animated by a studio.  The colors of the studios are as explained in previous plots.  Click and drag to zoom in.  Double click to zoom out.'



# The elements of this list are descriptions for the
# corresponding plot in the Performance tab on the
# Predictions page.
PLOT_DESC = list()
PLOT_DESC[['acc_vs_time']] = 'This chart shows the true positive (red) and false positive (black) rates for each six-month (two seasons) window from December 1999 (time = 1) to the present.  Each vertical rectangle  encapsulates two years; the leftmost point being the Winter and Spring seasons, and subsequent points being the following two seasons.  The true positive rate is defined as: (number of positives predicted correctly) / (number of positives predicted).  The false positive rate is defined analogously.  The performance is erratic due to the ever-changing quality of anime (two shows with everything identical other than their names can (and do) receive scores so different that one is below average and the other is above average.  As you can imagine, this confuses the classifier greatly).  Generally, when the classifier predicts a show to be above average, it is right about 70% of the time, while only about 60% of its predictions for below average shows are correct.'
PLOT_DESC[['tp_vs_tn']] = 'This is a plot of true positive vs. true negative.  Each point is the performance measured for one six-month period.  Like in the above plot, you can see that most of the positive predictions are correct at least 70% of the time.  Most negative predictions are correct at least 60% of the time.'
PLOT_DESC[['fp_vs_stucnt']] = 'This plot shows how well the classifier performs per studio.  Specifically, it plots the error as a function of the number of shows made by a studio.  The y-axis is the proportion of a studio\'s shows that were incorrectly predicted to be above average.  Generally, the more shows a studio has produced, the lower the error.  The horizontal dotted line is at FP = 0.3.  Points above this line are studios for which the classifier has trouble predicting that their shows will be good.  The points to the right of the rightmost vertical dotted line are the studios that have together produced 50% of all TV anime.  Points to the right of the middle vertical dotted line are studios that have together produced 67% of all TV anime.  Points to the right of the leftmost vertical dotted line are studios that have together produced 75% of all TV anime.  These lines bring good news: the classifier is accurate (error < 30%) at predicting that shows from most major studios will be good.  On the other hand, for those studios that consist of the remaining 25% of TV anime, the classifier is actually not too different, but is wrong more often.'
PLOT_DESC[['fn_vs_stucnt']] = 'This is the same plot as the above one, but displays the proportion of shows incorrectly predicted to be below average, rather than above average.  The shape is very similar, and the observations made in the above plot apply this one as well.  Again this is good since the quality of shows made by most major studios will generally be predicted correctly.'


# This is a description of the table that is shown in the
# Performance tab of the Predictions page.
PERF_TABLE_DESC = 'This table shows the classifier\'s performance for all studios.  The third column is the total TV anime shows produced by a studio.  The second column is the number of these correctly predicted to be below or above average.'

# The elements of ABOUT_TEXT is a paragraph, to be surrounded
# by <p> tags, for the About page.  Each element of ABOUT_LIST
# is text for the <li> tags in the list that appears in the
# About page.
ABOUT_TEXT = character()
ABOUT_LIST = character()
ABOUT_TEXT[1] = 'This website is intended to show various data about the world of anime.  The hope is to let anime viewers discover new things about anime: past, current, and future trends; the state of the industry; the performance of studios, genres, and source materials; and much more.  Here are some of the questions that you can find answers to with this site:'
ABOUT_TEXT[2] = 'All data used on this site is from the popular online anime database, MyAnimeList.  Data was gathered from their "Seasonal Anime" page, not from the individual pages of each show (that would take too long to get without overloading their servers).  As such, only a subset of the data for each show is used in this site.  Specifically, genres, air date, studio, number of episodes, number of viewers, anime type, and source material.  No data related to staff, in-show characters, or most of the data that can be found by visiting a specific show\'s page is used.  This is somewhat limiting, especially for fans who view staff and the like as an important factor for dermining the quality of a show, and leads to a lack of potentially interesting data to be analyzed and shown on this site.  However, the data available is more than sufficient, and provides ample information for making inferences and finding answers to many questions.'
ABOUT_TEXT[3] = 'Apart from allowing fans to view data about past and current anime, this site also allows fans to find out the quality of future anime.  By navigating to the "Predictions" page, fans can see which future anime are predicted to be above or below average.  This can be very useful in determing which shows to watch next season.  Although it is not correct 100% of the time (accuracy is closer to 70%), it can be used as a tool to discover new shows that one might have potentially not considered at all.  Currently, predictions are limited to only TV anime, as predictions for other types, such as OVAs and movies, are poor.'
ABOUT_TEXT[4] = 'This site is hosted on Shiny server from Rstudio.'

ABOUT_LIST[1] = 'Which studios are the most popular?'
ABOUT_LIST[2] = 'Which studios consistently produce good shows?'
ABOUT_LIST[3] = 'When was the golden age of a studio?'
ABOUT_LIST[4] = 'Which years had the best shows of a particular genre?'
ABOUT_LIST[5] = 'Which genres are associated with good shows?  Bad shows?'
ABOUT_LIST[6] = 'From which source materials are anime currently being produced?'
ABOUT_LIST[7] = 'Is anime better today than it was 10 years ago? 20 years ago?'
ABOUT_LIST[8] = 'Are OVA series better than TV series?'
ABOUT_LIST[9] = 'What was typical of anime in the early 2000s?'
ABOUT_LIST[10] = 'Will light novels become the main source of anime?'
ABOUT_LIST[11] = 'Are more shounen ai shows being produced?  If so, WHY?!?'
ABOUT_LIST[12] = 'Will this upcoming show be worth watching?'
ABOUT_LIST[13] = '...and much more!'
