library(shiny)
source('views/summaryView.R')
source('constants.R')
source('main5.R')

initTabs = function() {
    tabsetPanel(
                type="tabs",
                # input$tabpanelId is the name of the current tab.
                id='tabpanelId',
                # The argument to *Ouput(x) is the name of an R object
                # (defined in server.R as output$x) of type *.
                tabPanel(
                         "Summary", 
                         #summary.getView(),
                         fluidRow(
                                  column(
                                         10,
                                         plotOutput(
                                                    "plot1_1",
                                                    brush=brushOpts(
                                                                    id='plot1_1Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot1_1DblClick'
                                                    )
                                  ),
                                  column(
                                         2,
                                         checkboxInput(
                                                       'plot1_1MinCheckbox',
                                                       'Min',
                                                       FALSE
                                                       ),
                                         checkboxInput(
                                                       'plot1_1Q25Checkbox',
                                                       '25th percentile',
                                                       FALSE
                                                       ),
                                         checkboxInput(
                                                       'plot1_1MeanCheckbox',
                                                       'Mean',
                                                       FALSE
                                                       ),
                                         checkboxInput(
                                                       'plot1_1Q75Checkbox',
                                                       '75th percentile',
                                                       FALSE
                                                       ),
                                         checkboxInput(
                                                       'plot1_1MaxCheckbox',
                                                       'Max',
                                                       FALSE
                                                       )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         10,
                                         plotOutput(
                                                    "plot1_2",
                                                    brush=brushOpts(
                                                                    id='plot1_2Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot1_2DblClick'
                                                    )
                                         ),
                                  column(
                                         2,
                                         checkboxInput(
                                                       'plot1_2MinCheckbox',
                                                       'Min',
                                                       FALSE
                                                       ),
                                         checkboxInput(
                                                       'plot1_2Q25Checkbox',
                                                       '25th percentile',
                                                       FALSE
                                                       ),
                                         checkboxInput(
                                                       'plot1_2MeanCheckbox',
                                                       'Mean',
                                                       FALSE
                                                       ),
                                         checkboxInput(
                                                       'plot1_2Q75Checkbox',
                                                       '75th percentile',
                                                       FALSE
                                                       ),
                                         checkboxInput(
                                                       'plot1_2MaxCheckbox',
                                                       'Max',
                                                       FALSE
                                                       )
                                         )
                                  ),
                         fluidRow(
                                  #column(10, plotOutput("plot1_3")),
                                  column(
                                         10,
                                         plotOutput(
                                                    "plot1_3",
                                                    brush=brushOpts(
                                                                    id='plot1_3Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot1_3DblClick'
                                                    )
                                  ),
                                  column(
                                         2,
                                         checkboxInput(
                                                       'plot1_3MinCheckbox',
                                                       'Min',
                                                       FALSE
                                                       ),
                                         checkboxInput(
                                                       'plot1_3Q25Checkbox',
                                                       '25th percentile',
                                                       FALSE
                                                       ),
                                         checkboxInput(
                                                       'plot1_3MeanCheckbox',
                                                       'Mean',
                                                       FALSE
                                                       ),
                                         checkboxInput(
                                                       'plot1_3Q75Checkbox',
                                                       '75th percentile',
                                                       FALSE
                                                       ),
                                         checkboxInput(
                                                       'plot1_3MaxCheckbox',
                                                       'Max',
                                                       FALSE
                                                       )
                                         )
                                  ),
                         fluidRow(column(12, plotOutput("plot1_4"))),
                         fluidRow(column(12, plotOutput("plot1_5"))),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot1_6",
                                                    brush=brushOpts(
                                                                    id='plot1_6Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot1_6DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot1_7",
                                                    brush=brushOpts(
                                                                    id='plot1_7Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot1_7DblClick'
                                                    )
                                         )
                                  ),
                         value=TAB_ID_SUMMARY
                         ), 
                tabPanel(
                         "Genres",
                         #textOutput("genresView"),
                         #category.getView(),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot2_1",
                                                    brush=brushOpts(
                                                                    id='plot2_1Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot2_1DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot2_2",
                                                    brush=brushOpts(
                                                                    id='plot2_2Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot2_2DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         10,
                                         plotOutput(
                                                    "plot2_3",
                                                    brush=brushOpts(
                                                                    id='plot2_3Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot2_3DblClick'
                                                    )
                                         ),
                                  column(2,
                                         selectInput(
                                                     inputId='plot2_3SelectId',
                                                     label='Select genre',
                                                     choices=sort(names(globalDS)
                                                                  [6 : 44],
                                                                  decreasing=FALSE),
                                                     selected='Action'
                                                     )
                                         )
                                  ),
                         fluidRow(column(12, plotOutput("plot2_4"))),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot2_5",
                                                    brush=brushOpts(
                                                                    id='plot2_5Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot2_5DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot2_6",
                                                    brush=brushOpts(
                                                                    id='plot2_6Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot2_6DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot2_7",
                                                    brush=brushOpts(
                                                                    id='plot2_7Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot2_7DblClick'
                                                    )
                                         )
                                  ),
                         value=TAB_ID_GENRES
                         ),
                tabPanel(
                         "Sources",
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot3_1",
                                                    brush=brushOpts(
                                                                    id='plot3_1Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot3_1DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot3_2",
                                                    brush=brushOpts(
                                                                    id='plot3_2Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot3_2DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         10,
                                         plotOutput(
                                                    "plot3_3",
                                                    brush=brushOpts(
                                                                    id='plot3_3Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot3_3DblClick'
                                                    )
                                         ),
                                  column(2,
                                         selectInput(
                                                     inputId='plot3_3SelectId',
                                                     label='Select source',
                                                     choices=sort(levels(globalDS$
                                                                         source),
                                                                  decreasing=FALSE
                                                                  ),
                                                     selected='Manga'
                                                     )
                                         )
                                  ),
                         fluidRow(column(12, plotOutput("plot3_4"))),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot3_5",
                                                    brush=brushOpts(
                                                                    id='plot3_5Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot3_5DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot3_6",
                                                    brush=brushOpts(
                                                                    id='plot3_6Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot3_6DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot3_7",
                                                    brush=brushOpts(
                                                                    id='plot3_7Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot3_7DblClick'
                                                    )
                                         )
                                  ),
                         value=TAB_ID_SOURCES
                         ),
                tabPanel(
                         "Types",
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot4_1",
                                                    brush=brushOpts(
                                                                    id='plot4_1Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot4_1DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot4_2",
                                                    brush=brushOpts(
                                                                    id='plot4_2Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot4_2DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         10,
                                         plotOutput(
                                                    "plot4_3",
                                                    brush=brushOpts(
                                                                    id='plot4_3Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot4_3DblClick'
                                                    )
                                         ),
                                  column(2,
                                         selectInput(
                                                     inputId='plot4_3SelectId',
                                                     label='Select type',
                                                     choices=sort(levels(globalDS$
                                                                        type),
                                                                  decreasing=FALSE
                                                                  ),
                                                     selected='TV'
                                                     )
                                         )
                                  ),
                         fluidRow(column(12, plotOutput("plot4_4"))),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot4_5",
                                                    brush=brushOpts(
                                                                    id='plot4_5Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot4_5DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot4_6",
                                                    brush=brushOpts(
                                                                    id='plot4_6Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot4_6DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot4_7",
                                                    brush=brushOpts(
                                                                    id='plot4_7Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot4_7DblClick'
                                                    )
                                         )
                                  ),
                         value=TAB_ID_TYPES
                         ),
                tabPanel(
                         "Studios",
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot5_1",
                                                    brush=brushOpts(
                                                                    id='plot5_1Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot5_1DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot5_2",
                                                    brush=brushOpts(
                                                                    id='plot5_2Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot5_2DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         10,
                                         plotOutput(
                                                    "plot5_3",
                                                    brush=brushOpts(
                                                                    id='plot5_3Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot5_3DblClick'
                                                    )
                                         ),
                                  column(2,
                                         selectInput(
                                                     inputId='plot5_3SelectId',
                                                     label='Select studio',
                                                     choices=sort(levels(globalDS$
                                                                         studio),
                                                                  decreasing=FALSE
                                                                  )
                                                     #selected=''
                                                     )
                                         )
                                  ),
                         fluidRow(column(12, plotOutput("plot5_4"))),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot5_5",
                                                    brush=brushOpts(
                                                                    id='plot5_5Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot5_5DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot5_6",
                                                    brush=brushOpts(
                                                                    id='plot5_6Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot5_6DblClick'
                                                    )
                                         )
                                  ),
                         fluidRow(
                                  column(
                                         12,
                                         plotOutput(
                                                    "plot5_7",
                                                    brush=brushOpts(
                                                                    id='plot5_7Brush',
                                                                    resetOnNew=TRUE
                                                                    ),
                                                    dblclick='plot5_7DblClick'
                                                    )
                                         )
                                  ),
                         value=TAB_ID_STUDIOS
                         )
                )
}

initYearInput = function() {
    dateRangeInput(
                   'yearRangeInputWidget',
                   start='2000-01-01',
                   end='2010-01-01',
                   format='yyyy'
                   )
}

# Define UI for random distribution application 
fluidPage(
    
  # Application title
  titlePanel("Tabsets"),
  fluidRow(
           column(2,
                  selectInput(
                              inputId='studioSelectId',
                              label='Select studio',
                              choices=c('All studios',
                                        sort(levels(globalDS$studio))),
                              selected='All studios'
                              )
                  ),
           column(2,
                  selectInput(
                              inputId='genreSelectId',
                              label='Select genre',
                              choices=c('Any genre',
                                        sort(names(globalDS)[6 : 44])),
                              selected='Any genre'
                              )
                  ),
           column(2,
                  selectInput(
                              inputId='sourceSelectId',
                              label='Select source',
                              choices=c('Any source',
                                        sort(levels(globalDS$source))),
                              selected='Any source'
                              )
                  ),
           column(2,
                  selectInput(
                              inputId='typeSelectId',
                              label='Select type',
                              choices=c('Any type',
                                        sort(levels(globalDS$type))),
                              selected='Any type'
                              )
                  )
           ),
          actionButton('changeDataActionButton', 'Done'),
  # Sidebar with controls to select the random distribution type
  # and number of observations to generate. Note the use of the
  # br() element to introduce extra vertical spacing
  #sidebarLayout(
    #sidebarPanel(
      #radioButtons("dist", "Distribution type:",
                   #c("Normal" = "norm",
                     #"Uniform" = "unif",
                     #"Log-normal" = "lnorm",
                     #"Exponential" = "exp")),
      #br(),
      #
      #sliderInput("n", 
                  #"Number of observations:", 
                   #value = 500,
                   #min = 1, 
                   #max = 1000)
    #),
    
    # Show a tabset that includes a plot, summary, and table view
    # of the generated distribution
          initTabs()
  #)
)
