library(shiny)
source('views/summaryView.R')
source('constants.R')
source('main5.R')
source('tabs.R')
source('optionsPanel.R')


# Define UI for random distribution application 
fluidPage(
          tags$head(
                    tags$link(
                              rel="stylesheet",
                              type="text/css",
                              href="hover.css"
                              ),
                    tags$link(
                              rel="stylesheet",
                              type="text/css",
                              href="predictions.css"
                              ),
                    tags$link(
                              rel="stylesheet",
                              type="text/css",
                              href="performance.css"
                              ),
                    tags$link(
                              rel="stylesheet",
                              type="text/css",
                              href="options_panel.css"
                              ),
                    tags$link(
                              rel="stylesheet",
                              type="text/css",
                              href="about.css"
                              )
                    ),
          # Application title
          #titlePanel("Tabsets"),
          navbarPage(
                     'navbar',
                     tabPanel(
                              'Stats',
                              createOptionsPanel(),
                              initStatsTabs()
                              ),
                     tabPanel(
                              'Predictions',
                              initPredictionsTabs()
                              ),
                     navbarMenu(
                                'More',
                                tabPanel(
                                         'About',
                                         initAboutTab()
                                         ),
                                tabPanel(
                                         'Contact',
                                         tags$p(
                                                'Please contact me at: dekunutshooter@gmail.com'
                                                )
                                         )
                                )
                     )
)
